"""
Data models for the Source Discovery pipeline.

All adapters normalize results into CandidateSource.
The classifier produces ClassifiedCandidate.
The orchestrator returns DiscoveryResult.
"""

from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Optional, List, Dict, Any


@dataclass
class SearchQuery:
    """A single search query generated by the QueryPlanner."""
    query: str
    adapter: str  # "rss", "web", "github", "arxiv"
    source_config: str  # which config generated it, e.g. "vendors/siemens"
    tags: List[str] = field(default_factory=list)
    limit: int = 10
    days_back: Optional[int] = None  # Limit results to last N days (adapter-specific)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class CandidateSource:
    """Normalized candidate returned by any adapter."""
    title: str
    url: str
    snippet: Optional[str] = None
    source_type: str = "unknown"  # "rss_article", "github_repo", "web_page", etc.
    publisher: Optional[str] = None
    discovered_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    adapter: str = "unknown"  # which adapter found this
    query_used: Optional[str] = None
    raw_metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class Classification:
    """LLM classification output for a single candidate."""
    relevant: bool = False
    doc_type: str = "unknown"  # manual, whitepaper, spec, guide, app_note, docs, other
    topic_tags: List[str] = field(default_factory=list)
    authority_guess: str = "unknown"  # vendor_official, standards_body, community, academic, unknown
    confidence: float = 0.0  # 0.0 - 1.0
    reason: str = ""


@dataclass
class ClassifiedCandidate:
    """A candidate with its LLM classification attached."""
    candidate: CandidateSource
    classification: Classification
    cached: bool = False  # True if classification came from cache

    @property
    def approved(self) -> bool:
        return self.classification.relevant and self.classification.confidence >= 0.5

    def to_dict(self) -> dict:
        return {
            **self.candidate.to_dict(),
            "classification": asdict(self.classification),
            "cached": self.cached,
            "approved": self.approved,
        }


@dataclass
class DiscoveryResult:
    """Final output of a discovery run."""
    run_id: str
    started_at: str
    completed_at: Optional[str] = None
    queries_generated: int = 0
    candidates_found: int = 0
    candidates_approved: int = 0
    candidates_rejected: int = 0
    candidates_deduped: int = 0
    approved: List[ClassifiedCandidate] = field(default_factory=list)
    rejected: List[ClassifiedCandidate] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)

    def summary(self) -> dict:
        return {
            "run_id": self.run_id,
            "started_at": self.started_at,
            "completed_at": self.completed_at,
            "queries_generated": self.queries_generated,
            "candidates_found": self.candidates_found,
            "candidates_approved": self.candidates_approved,
            "candidates_rejected": self.candidates_rejected,
            "candidates_deduped": self.candidates_deduped,
            "errors": self.errors,
        }
